package com.example.ui.screens.progress

import android.content.Context
import android.content.Intent
import android.graphics.*
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import com.example.data.model.CurrentAffairsItem
import com.example.data.model.MistakeItem
import com.example.data.model.MockTestAttempt
import com.example.data.model.Question
import com.example.data.model.UserProfile
import org.json.JSONArray
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

object PdfReportGenerator {

    private const val PAGE_WIDTH = 595 // Standard A4 points at 72dpi
    private const val PAGE_HEIGHT = 842
    private const val MARGIN = 40f

    /**
     * Generates a comprehensive Mock Test Performance & Solution Review PDF
     */
    fun generateMockTestPdf(context: Context, attempt: MockTestAttempt): File {
        val reportDir = File(context.cacheDir, "reports").apply { mkdirs() }
        val dateStr = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date(attempt.timestamp))
        val cleanSubject = attempt.subject.replace("\\s+".toRegex(), "_")
        val outputFile = File(reportDir, "StudyMate_Test_${cleanSubject}_$dateStr.pdf")

        val pdfDocument = PdfDocument()
        var pageNumber = 1

        val paint = Paint(Paint.ANTI_ALIAS_FLAG)
        val textPaint = Paint(Paint.ANTI_ALIAS_FLAG)

        // Helper to start a new page
        fun createPage(): Pair<PdfDocument.Page, Canvas> {
            val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
            val page = pdfDocument.startPage(pageInfo)
            val canvas = page.canvas
            // Background
            canvas.drawColor(Color.WHITE)
            return Pair(page, canvas)
        }

        // Draw Header & Footer
        fun drawPageDecorations(canvas: Canvas, title: String, currentPage: Int) {
            // Header Top Bar
            paint.color = Color.rgb(15, 23, 42) // Dark Slate 900
            canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), 48f, paint)

            paint.color = Color.rgb(56, 189, 248) // Cyan accent line
            canvas.drawRect(0f, 48f, PAGE_WIDTH.toFloat(), 51f, paint)

            // Header Title
            textPaint.color = Color.WHITE
            textPaint.textSize = 12f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            canvas.drawText("StudyMate AI  |  Official Performance Report", MARGIN, 28f, textPaint)

            textPaint.color = Color.rgb(148, 163, 184)
            textPaint.textSize = 9f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            val timeText = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault()).format(Date(attempt.timestamp))
            canvas.drawText(timeText, PAGE_WIDTH - MARGIN - textPaint.measureText(timeText), 28f, textPaint)

            // Footer Bottom Bar
            paint.color = Color.rgb(241, 245, 249)
            canvas.drawRect(0f, PAGE_HEIGHT - 32f, PAGE_WIDTH.toFloat(), PAGE_HEIGHT.toFloat(), paint)

            textPaint.color = Color.rgb(100, 116, 139)
            textPaint.textSize = 8.5f
            canvas.drawText("Generated by StudyMate AI • Academic Diagnostic Report", MARGIN, PAGE_HEIGHT - 12f, textPaint)

            val pageStr = "Page $currentPage"
            canvas.drawText(pageStr, PAGE_WIDTH - MARGIN - textPaint.measureText(pageStr), PAGE_HEIGHT - 12f, textPaint)
        }

        // --- PAGE 1: Overview & Analytics ---
        var (currentPage, canvas) = createPage()
        drawPageDecorations(canvas, "Summary", pageNumber)

        var y = 75f

        // Title Block
        textPaint.color = Color.rgb(15, 23, 42)
        textPaint.textSize = 20f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("${attempt.examName} Mock Test Report", MARGIN, y, textPaint)
        y += 18f

        textPaint.color = Color.rgb(71, 85, 105)
        textPaint.textSize = 11f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText("${attempt.subject} • ${attempt.topic} • ${attempt.difficulty} Difficulty", MARGIN, y, textPaint)
        y += 24f

        // Score Card Box
        paint.color = Color.rgb(248, 250, 252)
        val scoreBoxRect = RectF(MARGIN, y, PAGE_WIDTH - MARGIN, y + 100f)
        canvas.drawRoundRect(scoreBoxRect, 12f, 12f, paint)
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 1f
        paint.color = Color.rgb(226, 232, 240)
        canvas.drawRoundRect(scoreBoxRect, 12f, 12f, paint)
        paint.style = Paint.Style.FILL

        // Inside Score Box: 4 Metric Columns
        val boxWidth = (PAGE_WIDTH - 2 * MARGIN) / 4
        val metrics = listOf(
            Pair("SCORE", "${attempt.score}"),
            Pair("ACCURACY", "${attempt.accuracyPercent.toInt()}%"),
            Pair("TIME SPENT", "${attempt.timeSpentSeconds / 60}m ${attempt.timeSpentSeconds % 60}s"),
            Pair("SPEED", "${if (attempt.totalQuestions > 0) attempt.timeSpentSeconds / attempt.totalQuestions else 0}s/Q")
        )

        metrics.forEachIndexed { i, metric ->
            val colX = MARGIN + i * boxWidth + boxWidth / 2
            textPaint.color = Color.rgb(100, 116, 139)
            textPaint.textSize = 8.5f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            val labelW = textPaint.measureText(metric.first)
            canvas.drawText(metric.first, colX - labelW / 2, y + 36f, textPaint)

            textPaint.color = if (i == 1 && attempt.accuracyPercent >= 70) Color.rgb(16, 185, 129)
                             else if (i == 1) Color.rgb(239, 68, 68)
                             else Color.rgb(15, 23, 42)
            textPaint.textSize = 22f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            val valW = textPaint.measureText(metric.second)
            canvas.drawText(metric.second, colX - valW / 2, y + 70f, textPaint)
        }

        y += 120f

        // Performance Breakdown Bar
        textPaint.color = Color.rgb(15, 23, 42)
        textPaint.textSize = 13f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Question Breakdown", MARGIN, y, textPaint)
        y += 14f

        val totalQ = if (attempt.totalQuestions > 0) attempt.totalQuestions else 1
        val correctRatio = attempt.correctCount.toFloat() / totalQ
        val incorrectRatio = attempt.incorrectCount.toFloat() / totalQ
        val skippedRatio = attempt.skippedCount.toFloat() / totalQ

        val barWidth = PAGE_WIDTH - 2 * MARGIN
        val barHeight = 16f
        var startX = MARGIN

        // Correct green bar
        if (correctRatio > 0) {
            paint.color = Color.rgb(16, 185, 129)
            val w = barWidth * correctRatio
            canvas.drawRoundRect(RectF(startX, y, startX + w, y + barHeight), 4f, 4f, paint)
            startX += w
        }
        // Incorrect red bar
        if (incorrectRatio > 0) {
            paint.color = Color.rgb(239, 68, 68)
            val w = barWidth * incorrectRatio
            canvas.drawRect(RectF(startX, y, startX + w, y + barHeight), paint)
            startX += w
        }
        // Skipped gray bar
        if (skippedRatio > 0) {
            paint.color = Color.rgb(148, 163, 184)
            val w = barWidth * skippedRatio
            canvas.drawRoundRect(RectF(startX, y, startX + w, y + barHeight), 4f, 4f, paint)
        }

        y += 30f

        // Legend row
        textPaint.textSize = 9.5f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        textPaint.color = Color.rgb(71, 85, 105)

        paint.color = Color.rgb(16, 185, 129)
        canvas.drawCircle(MARGIN + 6f, y - 4f, 5f, paint)
        canvas.drawText("Correct: ${attempt.correctCount}", MARGIN + 16f, y, textPaint)

        paint.color = Color.rgb(239, 68, 68)
        canvas.drawCircle(MARGIN + 120f + 6f, y - 4f, 5f, paint)
        canvas.drawText("Incorrect: ${attempt.incorrectCount}", MARGIN + 120f + 16f, y, textPaint)

        paint.color = Color.rgb(148, 163, 184)
        canvas.drawCircle(MARGIN + 240f + 6f, y - 4f, 5f, paint)
        canvas.drawText("Skipped: ${attempt.skippedCount}", MARGIN + 240f + 16f, y, textPaint)

        y += 28f

        // AI Diagnosis / Recommendation Card
        if (attempt.aiRecommendation.isNotBlank()) {
            paint.color = Color.rgb(240, 249, 255)
            val aiBoxRect = RectF(MARGIN, y, PAGE_WIDTH - MARGIN, y + 80f)
            canvas.drawRoundRect(aiBoxRect, 8f, 8f, paint)
            paint.style = Paint.Style.STROKE
            paint.strokeWidth = 1f
            paint.color = Color.rgb(186, 230, 253)
            canvas.drawRoundRect(aiBoxRect, 8f, 8f, paint)
            paint.style = Paint.Style.FILL

            textPaint.color = Color.rgb(3, 105, 161)
            textPaint.textSize = 10.5f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            canvas.drawText("✨ AI Learning Diagnosis & Recommendation", MARGIN + 12f, y + 20f, textPaint)

            textPaint.color = Color.rgb(51, 65, 85)
            textPaint.textSize = 9f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            drawWrappedText(canvas, attempt.aiRecommendation, MARGIN + 12f, y + 36f, PAGE_WIDTH - 2 * MARGIN - 24f, textPaint, 13f)

            y += 94f
        }

        // Weak and Strong Topics
        if (attempt.weakTopics.isNotEmpty() || attempt.strongTopics.isNotEmpty()) {
            val halfW = (PAGE_WIDTH - 2 * MARGIN - 12f) / 2
            
            // Strong Topics
            if (attempt.strongTopics.isNotEmpty()) {
                paint.color = Color.rgb(236, 253, 245)
                val stBox = RectF(MARGIN, y, MARGIN + halfW, y + 60f)
                canvas.drawRoundRect(stBox, 6f, 6f, paint)
                
                textPaint.color = Color.rgb(4, 120, 87)
                textPaint.textSize = 9.5f
                textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                canvas.drawText("💪 Strong Focus Areas", MARGIN + 8f, y + 16f, textPaint)
                
                textPaint.color = Color.rgb(6, 95, 70)
                textPaint.textSize = 8.5f
                textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
                var stY = y + 30f
                attempt.strongTopics.take(3).forEach {
                    canvas.drawText("• $it", MARGIN + 8f, stY, textPaint)
                    stY += 12f
                }
            }

            // Weak Topics
            if (attempt.weakTopics.isNotEmpty()) {
                val weakX = MARGIN + halfW + 12f
                paint.color = Color.rgb(254, 242, 242)
                val wtBox = RectF(weakX, y, weakX + halfW, y + 60f)
                canvas.drawRoundRect(wtBox, 6f, 6f, paint)

                textPaint.color = Color.rgb(185, 28, 28)
                textPaint.textSize = 9.5f
                textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                canvas.drawText("⚠️ Need Targeted Revision", weakX + 8f, y + 16f, textPaint)

                textPaint.color = Color.rgb(153, 27, 27)
                textPaint.textSize = 8.5f
                textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
                var wtY = y + 30f
                attempt.weakTopics.take(3).forEach {
                    canvas.drawText("• $it", weakX + 8f, wtY, textPaint)
                    wtY += 12f
                }
            }

            y += 74f
        }

        // Marking Scheme & Details
        textPaint.color = Color.rgb(100, 116, 139)
        textPaint.textSize = 9f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
        canvas.drawText("Marking Scheme: ${attempt.markingScheme} • Total Time Allowed: ${attempt.totalTimeAllowedSeconds / 60} minutes", MARGIN, y, textPaint)

        pdfDocument.finishPage(currentPage)

        // Write to file
        val fos = FileOutputStream(outputFile)
        pdfDocument.writeTo(fos)
        fos.flush()
        fos.close()
        pdfDocument.close()

        return outputFile
    }

    /**
     * Generates a complete Academic Portfolio & Analytics Summary PDF
     */
    fun generateAnalyticsSummaryPdf(
        context: Context,
        user: UserProfile?,
        attempts: List<MockTestAttempt>,
        mistakes: List<MistakeItem>,
        focusMinutes: Int,
        studyStreak: Int
    ): File {
        val reportDir = File(context.cacheDir, "reports").apply { mkdirs() }
        val dateStr = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
        val outputFile = File(reportDir, "StudyMate_Academic_Summary_$dateStr.pdf")

        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas = page.canvas
        canvas.drawColor(Color.WHITE)

        val paint = Paint(Paint.ANTI_ALIAS_FLAG)
        val textPaint = Paint(Paint.ANTI_ALIAS_FLAG)

        // Header Top Bar
        paint.color = Color.rgb(15, 23, 42)
        canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), 48f, paint)
        paint.color = Color.rgb(99, 102, 241) // Indigo accent
        canvas.drawRect(0f, 48f, PAGE_WIDTH.toFloat(), 51f, paint)

        textPaint.color = Color.WHITE
        textPaint.textSize = 12f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("StudyMate AI  |  Student Academic Analytics Portfolio", MARGIN, 28f, textPaint)

        textPaint.color = Color.rgb(148, 163, 184)
        textPaint.textSize = 9f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        val nowStr = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault()).format(Date())
        canvas.drawText(nowStr, PAGE_WIDTH - MARGIN - textPaint.measureText(nowStr), 28f, textPaint)

        var y = 75f

        // Student Profile Header
        val studentName = user?.name?.takeIf { it.isNotBlank() } ?: "Student"
        textPaint.color = Color.rgb(15, 23, 42)
        textPaint.textSize = 20f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Academic Progress Summary: $studentName", MARGIN, y, textPaint)
        y += 18f

        textPaint.color = Color.rgb(71, 85, 105)
        textPaint.textSize = 10f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        val targetExam = user?.examName?.takeIf { it.isNotBlank() } ?: "Competitive Exam"
        val grade = user?.grade?.takeIf { it.isNotBlank() } ?: "Class 12"
        canvas.drawText("Target: $targetExam • Level: $grade • Goal: ${user?.goal ?: "Top Rank"}", MARGIN, y, textPaint)
        y += 24f

        // High Level Metrics Box
        paint.color = Color.rgb(248, 250, 252)
        val metricBox = RectF(MARGIN, y, PAGE_WIDTH - MARGIN, y + 80f)
        canvas.drawRoundRect(metricBox, 10f, 10f, paint)
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 1f
        paint.color = Color.rgb(226, 232, 240)
        canvas.drawRoundRect(metricBox, 10f, 10f, paint)
        paint.style = Paint.Style.FILL

        val avgAccuracy = if (attempts.isNotEmpty()) attempts.map { it.accuracyPercent }.average().toInt() else 0
        val totalMocks = attempts.size
        val totalSolved = attempts.sumOf { it.totalQuestions }
        val masteredMistakes = mistakes.count { it.isMastered }

        val summaryMetrics = listOf(
            Pair("STUDY STREAK", "$studyStreak Days"),
            Pair("FOCUS TIME", "${focusMinutes / 60}h ${focusMinutes % 60}m"),
            Pair("MOCKS TAKEN", "$totalMocks Mocks"),
            Pair("AVG ACCURACY", "$avgAccuracy%")
        )

        val colW = (PAGE_WIDTH - 2 * MARGIN) / 4
        summaryMetrics.forEachIndexed { i, (label, value) ->
            val colX = MARGIN + i * colW + colW / 2
            textPaint.color = Color.rgb(100, 116, 139)
            textPaint.textSize = 8f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            val lW = textPaint.measureText(label)
            canvas.drawText(label, colX - lW / 2, y + 30f, textPaint)

            textPaint.color = Color.rgb(15, 23, 42)
            textPaint.textSize = 18f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            val vW = textPaint.measureText(value)
            canvas.drawText(value, colX - vW / 2, y + 60f, textPaint)
        }

        y += 105f

        // Subject-wise Breakdown Table
        textPaint.color = Color.rgb(15, 23, 42)
        textPaint.textSize = 13f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Subject-wise Performance & Mastery", MARGIN, y, textPaint)
        y += 14f

        val subjectGroups = attempts.groupBy { it.subject }
        if (subjectGroups.isNotEmpty()) {
            // Table Header
            paint.color = Color.rgb(241, 245, 249)
            canvas.drawRect(MARGIN, y, PAGE_WIDTH - MARGIN, y + 24f, paint)

            textPaint.color = Color.rgb(51, 65, 85)
            textPaint.textSize = 9f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            canvas.drawText("Subject", MARGIN + 10f, y + 16f, textPaint)
            canvas.drawText("Tests", MARGIN + 180f, y + 16f, textPaint)
            canvas.drawText("Questions", MARGIN + 260f, y + 16f, textPaint)
            canvas.drawText("Avg Accuracy", MARGIN + 360f, y + 16f, textPaint)
            canvas.drawText("Status", PAGE_WIDTH - MARGIN - 60f, y + 16f, textPaint)
            y += 24f

            subjectGroups.forEach { (sub, subAttempts) ->
                val subAcc = subAttempts.map { it.accuracyPercent }.average().toInt()
                val subQ = subAttempts.sumOf { it.totalQuestions }
                val isStrong = subAcc >= 70

                paint.color = Color.rgb(255, 255, 255)
                canvas.drawRect(MARGIN, y, PAGE_WIDTH - MARGIN, y + 22f, paint)
                paint.color = Color.rgb(241, 245, 249)
                canvas.drawLine(MARGIN, y + 22f, PAGE_WIDTH - MARGIN, y + 22f, paint)

                textPaint.color = Color.rgb(15, 23, 42)
                textPaint.textSize = 9f
                textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
                canvas.drawText(sub, MARGIN + 10f, y + 15f, textPaint)
                canvas.drawText("${subAttempts.size}", MARGIN + 180f, y + 15f, textPaint)
                canvas.drawText("$subQ", MARGIN + 260f, y + 15f, textPaint)

                textPaint.color = if (isStrong) Color.rgb(16, 185, 129) else Color.rgb(239, 68, 68)
                textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                canvas.drawText("$subAcc%", MARGIN + 360f, y + 15f, textPaint)

                textPaint.color = if (isStrong) Color.rgb(4, 120, 87) else Color.rgb(185, 28, 28)
                canvas.drawText(if (isStrong) "Strong" else "Needs Review", PAGE_WIDTH - MARGIN - 60f, y + 15f, textPaint)

                y += 22f
            }
            y += 18f
        } else {
            textPaint.color = Color.rgb(148, 163, 184)
            textPaint.textSize = 9.5f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
            canvas.drawText("No mock test attempts recorded yet. Take a test to view subject diagnostics.", MARGIN, y + 14f, textPaint)
            y += 30f
        }

        // Mistake Book Summary
        textPaint.color = Color.rgb(15, 23, 42)
        textPaint.textSize = 13f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Mistake Book Mastery Status", MARGIN, y, textPaint)
        y += 14f

        val totalMistakes = mistakes.size
        paint.color = Color.rgb(248, 250, 252)
        val mbBox = RectF(MARGIN, y, PAGE_WIDTH - MARGIN, y + 54f)
        canvas.drawRoundRect(mbBox, 8f, 8f, paint)

        textPaint.color = Color.rgb(51, 65, 85)
        textPaint.textSize = 9.5f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText("Total Mistakes Logged: $totalMistakes  |  Mastered: $masteredMistakes  |  Pending Review: ${totalMistakes - masteredMistakes}", MARGIN + 12f, y + 22f, textPaint)

        val mbProgress = if (totalMistakes > 0) masteredMistakes.toFloat() / totalMistakes else 0f
        paint.color = Color.rgb(226, 232, 240)
        canvas.drawRoundRect(RectF(MARGIN + 12f, y + 32f, PAGE_WIDTH - MARGIN - 12f, y + 42f), 4f, 4f, paint)
        if (mbProgress > 0) {
            paint.color = Color.rgb(16, 185, 129)
            canvas.drawRoundRect(RectF(MARGIN + 12f, y + 32f, MARGIN + 12f + (PAGE_WIDTH - 2 * MARGIN - 24f) * mbProgress, y + 42f), 4f, 4f, paint)
        }

        y += 70f

        // Recent Mock Tests History Table
        if (attempts.isNotEmpty()) {
            textPaint.color = Color.rgb(15, 23, 42)
            textPaint.textSize = 13f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            canvas.drawText("Recent Mock Tests History", MARGIN, y, textPaint)
            y += 14f

            attempts.take(4).forEach { att ->
                val dateFmt = SimpleDateFormat("dd MMM", Locale.getDefault()).format(Date(att.timestamp))
                paint.color = Color.rgb(248, 250, 252)
                canvas.drawRoundRect(RectF(MARGIN, y, PAGE_WIDTH - MARGIN, y + 26f), 6f, 6f, paint)

                textPaint.color = Color.rgb(15, 23, 42)
                textPaint.textSize = 9f
                textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                canvas.drawText(att.title, MARGIN + 10f, y + 17f, textPaint)

                textPaint.color = Color.rgb(100, 116, 139)
                textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
                canvas.drawText("${att.subject} • $dateFmt", MARGIN + 220f, y + 17f, textPaint)

                textPaint.color = if (att.accuracyPercent >= 70) Color.rgb(16, 185, 129) else Color.rgb(239, 68, 68)
                textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                canvas.drawText("${att.accuracyPercent.toInt()}% Acc (${att.score} marks)", PAGE_WIDTH - MARGIN - 120f, y + 17f, textPaint)

                y += 30f
            }
        }

        // Footer
        paint.color = Color.rgb(241, 245, 249)
        canvas.drawRect(0f, PAGE_HEIGHT - 32f, PAGE_WIDTH.toFloat(), PAGE_HEIGHT.toFloat(), paint)
        textPaint.color = Color.rgb(100, 116, 139)
        textPaint.textSize = 8.5f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText("StudyMate AI Academic Diagnostic System • Verified Student Record", MARGIN, PAGE_HEIGHT - 12f, textPaint)

        pdfDocument.finishPage(page)

        val fos = FileOutputStream(outputFile)
        pdfDocument.writeTo(fos)
        fos.flush()
        fos.close()
        pdfDocument.close()

        return outputFile
    }

    /**
     * Shares a generated PDF file via Android Share Intent
     */
    fun sharePdfReport(context: Context, pdfFile: File, shareTitle: String = "StudyMate AI Report") {
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            pdfFile
        )

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, shareTitle)
            putExtra(Intent.EXTRA_TEXT, "Here is the official document generated by StudyMate AI NOVA.")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }

        val chooser = Intent.createChooser(intent, "Share Document via")
        chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(chooser)
    }

    /**
     * Generates a beautifully formatted Current Affairs PDF report with Date, Category, Summary, Exam Relevance and Source metadata.
     */
    fun generateCurrentAffairsPdf(
        context: Context,
        items: List<CurrentAffairsItem>,
        dateStr: String,
        language: String,
        examName: String
    ): File {
        val reportDir = File(context.cacheDir, "reports").apply { mkdirs() }
        val sanitizedDate = dateStr.replace("[^a-zA-Z0-9_-]".toRegex(), "_")
        val outputFile = File(reportDir, "CurrentAffairs_${sanitizedDate}_${System.currentTimeMillis()}.pdf")

        val pdfDocument = PdfDocument()
        var pageNumber = 1

        val paint = Paint(Paint.ANTI_ALIAS_FLAG)
        val textPaint = Paint(Paint.ANTI_ALIAS_FLAG)

        fun createPage(): Pair<PdfDocument.Page, Canvas> {
            val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
            val page = pdfDocument.startPage(pageInfo)
            val canvas = page.canvas
            canvas.drawColor(Color.WHITE)
            return Pair(page, canvas)
        }

        fun drawPageDecorations(canvas: Canvas, title: String, currentPage: Int) {
            // Header Top Bar
            paint.color = Color.rgb(15, 23, 42) // Dark Slate 900
            canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), 44f, paint)

            paint.color = Color.rgb(56, 189, 248) // Cyan accent line
            canvas.drawRect(0f, 44f, PAGE_WIDTH.toFloat(), 47f, paint)

            // Header Title
            textPaint.color = Color.WHITE
            textPaint.textSize = 11f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            canvas.drawText("StudyMate AI • Current Affairs Intelligence", MARGIN, 28f, textPaint)

            textPaint.color = Color.rgb(203, 213, 225)
            textPaint.textSize = 9.5f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            val rightText = "$dateStr | $language"
            canvas.drawText(rightText, PAGE_WIDTH - MARGIN - textPaint.measureText(rightText), 28f, textPaint)

            // Bottom Footer
            paint.color = Color.rgb(241, 245, 249)
            canvas.drawRect(0f, PAGE_HEIGHT - 32f, PAGE_WIDTH.toFloat(), PAGE_HEIGHT.toFloat(), paint)

            textPaint.color = Color.rgb(100, 116, 139)
            textPaint.textSize = 8.5f
            canvas.drawText("StudyMate AI • Target: $examName • Verified Real Data", MARGIN, PAGE_HEIGHT - 12f, textPaint)

            val pageStr = "Page $currentPage"
            canvas.drawText(pageStr, PAGE_WIDTH - MARGIN - textPaint.measureText(pageStr), PAGE_HEIGHT - 12f, textPaint)
        }

        var (currentPage, canvas) = createPage()
        drawPageDecorations(canvas, "Current Affairs", pageNumber)
        var currentY = 70f

        // Document Title Banner on first page
        paint.color = Color.rgb(248, 250, 252)
        canvas.drawRoundRect(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY + 54f, 8f, 8f, paint)

        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 1f
        paint.color = Color.rgb(226, 232, 240)
        canvas.drawRoundRect(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY + 54f, 8f, 8f, paint)
        paint.style = Paint.Style.FILL

        textPaint.color = Color.rgb(15, 23, 42)
        textPaint.textSize = 15f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Daily Current Affairs Dossier — $dateStr", MARGIN + 12f, currentY + 24f, textPaint)

        textPaint.color = Color.rgb(71, 85, 105)
        textPaint.textSize = 9.5f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText("Exam Target: $examName • Total Topics: ${items.size} • Verified Academic Sources", MARGIN + 12f, currentY + 42f, textPaint)

        currentY += 70f

        // Render each Current Affairs Item
        items.forEachIndexed { index, item ->
            // Estimated block height ~ 100-130f
            if (currentY > PAGE_HEIGHT - 140f) {
                pdfDocument.finishPage(currentPage)
                pageNumber++
                val next = createPage()
                currentPage = next.first
                canvas = next.second
                drawPageDecorations(canvas, "Current Affairs", pageNumber)
                currentY = 65f
            }

            val cardStartY = currentY

            // Card background
            paint.color = Color.rgb(255, 255, 255)
            paint.style = Paint.Style.FILL
            canvas.drawRoundRect(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY + 105f, 6f, 6f, paint)

            paint.style = Paint.Style.STROKE
            paint.strokeWidth = 1f
            paint.color = Color.rgb(226, 232, 240)
            canvas.drawRoundRect(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY + 105f, 6f, 6f, paint)
            paint.style = Paint.Style.FILL

            // Category tag badge
            paint.color = Color.rgb(224, 242, 254) // Light sky
            canvas.drawRoundRect(MARGIN + 10f, currentY + 8f, MARGIN + 95f, currentY + 22f, 4f, 4f, paint)
            textPaint.color = Color.rgb(2, 132, 199)
            textPaint.textSize = 8.5f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            val catText = item.category.take(16)
            canvas.drawText(catText, MARGIN + 16f, currentY + 18f, textPaint)

            // Date / Source
            textPaint.color = Color.rgb(100, 116, 139)
            textPaint.textSize = 8.5f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            val metaStr = "${item.publishedDate} • Source: ${item.sourceName}"
            canvas.drawText(metaStr, PAGE_WIDTH - MARGIN - 12f - textPaint.measureText(metaStr), currentY + 18f, textPaint)

            // Headline
            textPaint.color = Color.rgb(15, 23, 42)
            textPaint.textSize = 11f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            val headline = "${index + 1}. ${item.title}"
            drawWrappedText(canvas, headline, MARGIN + 10f, currentY + 36f, PAGE_WIDTH - (MARGIN * 2) - 20f, textPaint, 13f)

            // Summary
            textPaint.color = Color.rgb(51, 65, 85)
            textPaint.textSize = 9f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            drawWrappedText(canvas, item.summary, MARGIN + 10f, currentY + 54f, PAGE_WIDTH - (MARGIN * 2) - 20f, textPaint, 11.5f)

            // Exam Relevance
            textPaint.color = Color.rgb(3, 105, 161)
            textPaint.textSize = 8.5f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            val relStr = "🎯 Exam Relevance: ${item.examRelevance}"
            drawWrappedText(canvas, relStr, MARGIN + 10f, currentY + 88f, PAGE_WIDTH - (MARGIN * 2) - 20f, textPaint, 11f)

            currentY += 118f
        }

        pdfDocument.finishPage(currentPage)

        val fos = FileOutputStream(outputFile)
        pdfDocument.writeTo(fos)
        fos.flush()
        fos.close()
        pdfDocument.close()

        return outputFile
    }

    /**
     * Generates a clean PDF for long NOVA answers with Topic, Date, Language, Formatted Markdown and Page Numbers.
     */
    fun generateNovaAnswerPdf(
        context: Context,
        topicTitle: String,
        contentMarkdown: String,
        language: String,
        sources: List<String> = emptyList()
    ): File {
        val reportDir = File(context.cacheDir, "reports").apply { mkdirs() }
        val cleanTopic = topicTitle.replace("[^a-zA-Z0-9_-]".toRegex(), "_").take(30)
        val outputFile = File(reportDir, "NOVA_Notes_${cleanTopic}_${System.currentTimeMillis()}.pdf")

        val pdfDocument = PdfDocument()
        var pageNumber = 1

        val paint = Paint(Paint.ANTI_ALIAS_FLAG)
        val textPaint = Paint(Paint.ANTI_ALIAS_FLAG)
        val dateStr = SimpleDateFormat("dd MMM yyyy", Locale.getDefault()).format(Date())

        fun createPage(): Pair<PdfDocument.Page, Canvas> {
            val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
            val page = pdfDocument.startPage(pageInfo)
            val canvas = page.canvas
            canvas.drawColor(Color.WHITE)
            return Pair(page, canvas)
        }

        fun drawPageDecorations(canvas: Canvas, title: String, currentPage: Int) {
            // Header Top Bar
            paint.color = Color.rgb(15, 23, 42)
            canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), 44f, paint)

            paint.color = Color.rgb(99, 102, 241) // Indigo accent
            canvas.drawRect(0f, 44f, PAGE_WIDTH.toFloat(), 47f, paint)

            // Header Title
            textPaint.color = Color.WHITE
            textPaint.textSize = 11f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            canvas.drawText("StudyMate AI • NOVA Academic Notes", MARGIN, 28f, textPaint)

            textPaint.color = Color.rgb(203, 213, 225)
            textPaint.textSize = 9.5f
            textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            val rightText = "$dateStr | $language"
            canvas.drawText(rightText, PAGE_WIDTH - MARGIN - textPaint.measureText(rightText), 28f, textPaint)

            // Footer
            paint.color = Color.rgb(241, 245, 249)
            canvas.drawRect(0f, PAGE_HEIGHT - 32f, PAGE_WIDTH.toFloat(), PAGE_HEIGHT.toFloat(), paint)

            textPaint.color = Color.rgb(100, 116, 139)
            textPaint.textSize = 8.5f
            canvas.drawText("Generated by NOVA Personal AI Study Coach", MARGIN, PAGE_HEIGHT - 12f, textPaint)

            val pageStr = "Page $currentPage"
            canvas.drawText(pageStr, PAGE_WIDTH - MARGIN - textPaint.measureText(pageStr), PAGE_HEIGHT - 12f, textPaint)
        }

        var (currentPage, canvas) = createPage()
        drawPageDecorations(canvas, topicTitle, pageNumber)
        var currentY = 70f

        // Title Header
        paint.color = Color.rgb(248, 250, 252)
        canvas.drawRoundRect(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY + 48f, 8f, 8f, paint)
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 1f
        paint.color = Color.rgb(226, 232, 240)
        canvas.drawRoundRect(MARGIN, currentY, PAGE_WIDTH - MARGIN, currentY + 48f, 8f, 8f, paint)
        paint.style = Paint.Style.FILL

        textPaint.color = Color.rgb(15, 23, 42)
        textPaint.textSize = 14f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText(topicTitle.take(50), MARGIN + 12f, currentY + 22f, textPaint)

        textPaint.color = Color.rgb(100, 116, 139)
        textPaint.textSize = 9f
        textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        canvas.drawText("Topic Dossier • $dateStr • Language: $language", MARGIN + 12f, currentY + 38f, textPaint)

        currentY += 64f

        // Body content paragraphs
        val lines = contentMarkdown.split("\n")
        for (rawLine in lines) {
            val trimmed = rawLine.trim()
            if (trimmed.isEmpty()) {
                currentY += 8f
                continue
            }

            if (currentY > PAGE_HEIGHT - 70f) {
                pdfDocument.finishPage(currentPage)
                pageNumber++
                val next = createPage()
                currentPage = next.first
                canvas = next.second
                drawPageDecorations(canvas, topicTitle, pageNumber)
                currentY = 65f
            }

            when {
                trimmed.startsWith("###") || trimmed.startsWith("##") || trimmed.startsWith("#") -> {
                    currentY += 6f
                    val heading = trimmed.removePrefix("#").removePrefix("#").removePrefix("#").trim()
                    textPaint.color = Color.rgb(30, 41, 59)
                    textPaint.textSize = 11.5f
                    textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                    drawWrappedText(canvas, heading, MARGIN, currentY, PAGE_WIDTH - (MARGIN * 2), textPaint, 14f)
                    currentY += 16f
                }
                trimmed.startsWith("-") || trimmed.startsWith("*") || trimmed.startsWith("•") -> {
                    val bulletText = "•  " + trimmed.substring(1).trim()
                    textPaint.color = Color.rgb(51, 65, 85)
                    textPaint.textSize = 9.5f
                    textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
                    drawWrappedText(canvas, bulletText, MARGIN + 8f, currentY, PAGE_WIDTH - (MARGIN * 2) - 8f, textPaint, 13f)
                    currentY += 15f
                }
                else -> {
                    textPaint.color = Color.rgb(51, 65, 85)
                    textPaint.textSize = 9.5f
                    textPaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
                    drawWrappedText(canvas, trimmed, MARGIN, currentY, PAGE_WIDTH - (MARGIN * 2), textPaint, 13f)
                    currentY += 15f
                }
            }
        }

        pdfDocument.finishPage(currentPage)

        val fos = FileOutputStream(outputFile)
        pdfDocument.writeTo(fos)
        fos.flush()
        fos.close()
        pdfDocument.close()

        return outputFile
    }

    private fun drawWrappedText(canvas: Canvas, text: String, x: Float, startY: Float, maxWidth: Float, paint: Paint, lineHeight: Float) {
        val words = text.split(" ")
        var line = ""
        var currentY = startY

        for (word in words) {
            val testLine = if (line.isEmpty()) word else "$line $word"
            if (paint.measureText(testLine) > maxWidth) {
                canvas.drawText(line, x, currentY, paint)
                line = word
                currentY += lineHeight
            } else {
                line = testLine
            }
        }
        if (line.isNotEmpty()) {
            canvas.drawText(line, x, currentY, paint)
        }
    }
}
