package com.example.localization

object AppStrings {
    private val englishMap = mapOf(
        // App Identity & Common Navigation
        "app_name" to "StudyMate AI",
        "nav_home" to "Home",
        "nav_learn" to "Learn",
        "nav_study" to "Study Hub",
        "nav_focus" to "Focus",
        "nav_practice" to "Practice",
        "nav_updates" to "Updates",
        "nav_ai_tutor" to "AI Tutor",
        "nav_nova" to "NOVA AI",
        "nav_profile" to "Profile & Settings",
        "nav_notifications" to "Notification Center",
        "nav_daily_briefing" to "Daily Briefing",
        "nav_smart_planner" to "Smart Planner",
        "nav_schedule" to "Study Schedule",
        "nav_revision" to "Revision Hub",
        "nav_doc_summarizer" to "Document Summarizer",
        "nav_exam_readiness" to "Exam Readiness",
        "nav_vacancies" to "Smart Vacancies",
        "nav_live_exam" to "Live Exam Intelligence",

        // Auth & Accounts
        "auth_welcome_back" to "Welcome Back",
        "auth_login_subtitle" to "Sign in to continue your exam preparation",
        "auth_email_label" to "Email Address",
        "auth_email_hint" to "student@example.com",
        "auth_password_label" to "Password",
        "auth_password_hint" to "Enter your password",
        "auth_login_btn" to "Sign In",
        "auth_signup_btn" to "Create Account",
        "auth_dont_have_account" to "Don't have an account?",
        "auth_already_have_account" to "Already have an account?",
        "auth_forgot_password" to "Forgot Password?",
        "auth_sign_in_google" to "Continue with Google",
        "auth_continue_guest" to "Explore as Guest",
        "auth_create_account_title" to "Create Free Account",
        "auth_name_label" to "Full Name",
        "auth_name_hint" to "Your Name",
        "auth_confirm_password" to "Confirm Password",
        "auth_otp_title" to "Verify Security Code",
        "auth_otp_subtitle" to "Enter the 6-digit verification code sent to your email",
        "auth_verify_btn" to "Verify & Proceed",
        "auth_resend_otp" to "Resend Code",
        "auth_sign_out" to "Sign Out",
        "auth_delete_account" to "Delete Account",

        // Top App Bar & Universal Actions
        "action_back" to "Back",
        "action_save" to "Save",
        "action_saved" to "Saved",
        "action_share" to "Share",
        "action_download" to "Download",
        "action_search" to "Search",
        "action_filter" to "Filter",
        "action_sort" to "Sort",
        "action_clear" to "Clear",
        "action_clear_all" to "Clear All",
        "action_apply" to "Apply",
        "action_cancel" to "Cancel",
        "action_confirm" to "Confirm",
        "action_done" to "Done",
        "action_close" to "Close",
        "action_refresh" to "Refresh",
        "action_retry" to "Retry",
        "action_delete" to "Delete",
        "action_edit" to "Edit",
        "action_view_all" to "View All",
        "action_view_details" to "View Details",
        "action_start" to "Start",
        "action_resume" to "Resume",
        "action_pause" to "Pause",
        "action_stop" to "Stop",
        "action_submit" to "Submit",
        "action_next" to "Next",
        "action_previous" to "Previous",
        "action_switch_language" to "Change Language",
        "language_current" to "English",
        "language_en" to "English",
        "language_hi" to "हिन्दी",

        // Home Screen
        "home_greeting" to "Welcome, %s 👋",
        "home_exam_countdown" to "%d Days Until Exam",
        "home_target_exam" to "Target Exam: %s",
        "home_daily_missions" to "Today's Study Missions",
        "home_all_missions_done" to "All missions completed! Outstanding work 🎉",
        "home_quick_actions" to "Quick Study Hub",
        "home_action_learn" to "Learn & Study",
        "home_action_practice" to "Mock Test",
        "home_action_updates" to "Govt Jobs & Updates",
        "home_action_focus" to "Focus Shield",
        "home_action_nova" to "Ask NOVA AI",
        "home_readiness_score" to "Exam Readiness Score",
        "home_ai_recommendation" to "AI Study Coach Recommendation",
        "home_study_now" to "Recommended Right Now",
        "home_live_updates_title" to "Live Exam Alerts & News",
        "home_vacancies_title" to "Trending Vacancies & Jobs",
        "home_continue_session" to "Resume Incomplete Test",

        // Learn Hub & Chapters
        "learn_hub_title" to "Study & Learning Hub",
        "learn_hub_subtitle" to "Comprehensive syllabus, notes, formulas & concepts",
        "learn_tab_all_subjects" to "Syllabus Tree",
        "learn_tab_materials" to "Study Materials",
        "learn_tab_notes" to "Smart Notes",
        "learn_tab_formulas" to "Formula Vault",
        "learn_tab_current_affairs" to "Current Affairs",
        "learn_tab_doubts" to "Socratic Doubt Solver",
        "learn_chapters_count" to "%d Chapters",
        "learn_topics_count" to "%d Topics",
        "learn_mastery_level" to "Mastery: %d%%",
        "learn_read_aloud" to "Read Aloud",
        "learn_key_points" to "High-Yield Summary",
        "learn_practice_this" to "Practice Topic Questions",
        "learn_ask_doubt" to "Ask NOVA about this topic",
        "learn_mark_mastered" to "Mark as Mastered",

        // Smart Vacancies & Updates Hub
        "vacancy_hub_title" to "Government Jobs & Exam Updates",
        "vacancy_hub_subtitle" to "Official notifications, admit cards, answer keys & results",
        "vacancy_tab_all" to "Vacancies",
        "vacancy_tab_admit_card" to "Admit Cards",
        "vacancy_tab_results" to "Exam Results",
        "vacancy_tab_answer_key" to "Answer Keys",
        "vacancy_tab_admission" to "Admissions",
        "vacancy_tab_saved" to "Saved & Tracked",
        "vacancy_tab_alerts" to "Notification Alerts",
        "vacancy_filter_all_states" to "All India & States",
        "vacancy_filter_category" to "Job Category",
        "vacancy_search_placeholder" to "Search vacancy, board, post, state...",
        "vacancy_last_date" to "Last Date: %s",
        "vacancy_posts_count" to "%s Posts",
        "vacancy_eligibility" to "Eligibility & Qualification",
        "vacancy_age_limit" to "Age Limit",
        "vacancy_salary" to "Salary / Pay Scale",
        "vacancy_apply_online" to "Apply Online (Official Link)",
        "vacancy_download_pdf" to "Official Notification PDF",
        "vacancy_selection_process" to "Selection Process",
        "vacancy_syllabus" to "Exam Pattern & Syllabus",
        "vacancy_important_dates" to "Important Dates Timeline",
        "vacancy_fee_details" to "Application Fee",
        "vacancy_set_reminder" to "Set Deadline Reminder",
        "vacancy_track_application" to "Track My Application",
        "vacancy_find_jobs_btn" to "Find Jobs For My Qualification",
        "vacancy_saved_empty" to "No saved vacancies yet. Bookmark jobs to track them here.",

        // Focus Mode & App Shield
        "focus_title" to "Deep Work Focus Session",
        "focus_subtitle" to "Distraction-free study with active app blocker",
        "focus_start_session" to "Start Focus Timer",
        "focus_pause_session" to "Pause Session",
        "focus_resume_session" to "Resume Focus",
        "focus_end_session" to "End Session",
        "focus_strict_mode" to "Strict App Lock",
        "focus_strict_desc" to "Blocks all distracting apps during the session",
        "focus_take_break" to "Take a 5-Min Break",
        "focus_break_running" to "Break Time Active",
        "focus_streak_banner" to "🔥 %d Day Study Streak!",
        "focus_session_completed" to "Session Completed! Great Focus 🎉",
        "focus_xp_earned" to "+%d Study XP Earned",

        // Practice & Mock Tests
        "practice_title" to "Test Series & Practice Hub",
        "practice_subtitle" to "PYQs, speed drills, full mocks & AI mistake diagnosis",
        "practice_start_full_mock" to "Start Full Mock Test",
        "practice_start_speed_test" to "10-Min Speed Drill",
        "practice_start_topic_quiz" to "Targeted Topic Practice",
        "practice_question_palette" to "Question Palette",
        "practice_mark_review" to "Mark for Review",
        "practice_clear_response" to "Clear Response",
        "practice_save_next" to "Save & Next",
        "practice_submit_confirm_title" to "Submit Mock Test?",
        "practice_submit_confirm_desc" to "Are you sure you want to submit? You have %d answered, %d marked for review, and %d unanswered questions.",
        "practice_scorecard_title" to "Test Result & Scorecard",
        "practice_score_label" to "Score: %d / %d",
        "practice_accuracy_label" to "Accuracy: %.1f%%",
        "practice_time_spent" to "Time Spent: %s",
        "practice_review_solutions" to "Review Step-by-Step Solutions",
        "practice_retry_wrong" to "Retry Incorrect Questions",
        "practice_mistake_book" to "Mistake Notebook",

        // NOVA AI Tutor
        "nova_title" to "NOVA AI Academic Mentor",
        "nova_subtitle" to "24/7 personalized exam doubt solver & conceptual tutor",
        "nova_prompt_hint" to "Ask any academic doubt, formula derivation, or concept...",
        "nova_thinking_mode" to "Deep Thinking Derivation Mode",
        "nova_quick_actions" to "Quick AI Actions",
        "nova_action_summarize" to "Summarize Topic",
        "nova_action_derivation" to "Step-by-Step Math",
        "nova_action_mcq" to "Generate Practice MCQs",
        "nova_action_flashcards" to "Create Flashcards",

        // Settings & Profile
        "settings_title" to "Settings & Account",
        "settings_language_section" to "Language & Localization 🌐",
        "settings_language_desc" to "Switch app language between English and Hindi globally",
        "settings_theme_section" to "App Theme & Appearance 🎨",
        "settings_notifications_section" to "Smart Notifications 🔔",
        "settings_exam_section" to "Exam & Target Goals 🎓",
        "settings_change_exam" to "Change Selected Exam",
        "settings_daily_hours" to "Daily Target Hours",
        "settings_clear_cache" to "Clear Translation & Offline Cache",
        "settings_sync_data" to "Sync Data with Cloud",

        // General States & Messages
        "state_loading" to "Loading...",
        "state_no_data" to "No records found",
        "state_error" to "Something went wrong. Please try again.",
        "state_offline" to "Working in offline mode",
        "toast_lang_switched" to "Language switched to %s",
        "toast_back_exit" to "Press Back again to exit StudyMate"
    )

    private val hindiMap = mapOf(
        // App Identity & Common Navigation
        "app_name" to "स्टडीमेट एआई",
        "nav_home" to "होम",
        "nav_learn" to "पढ़ाई",
        "nav_study" to "अध्ययन हब",
        "nav_focus" to "फोकस",
        "nav_practice" to "अभ्यास",
        "nav_updates" to "अपडेट्स",
        "nav_ai_tutor" to "एआई ट्यूटर",
        "nav_nova" to "नोवा एआई",
        "nav_profile" to "प्रोफाइल और सेटिंग्स",
        "nav_notifications" to "सूचना केंद्र",
        "nav_daily_briefing" to "दैनिक ब्रीफिंग",
        "nav_smart_planner" to "स्मार्ट प्लानर",
        "nav_schedule" to "अध्ययन समय सारणी",
        "nav_revision" to "रिवीजन हब",
        "nav_doc_summarizer" to "दस्तावेज़ सारांश",
        "nav_exam_readiness" to "परीक्षा तैयारी",
        "nav_vacancies" to "स्मार्ट वेकेंसी",
        "nav_live_exam" to "लाइव परीक्षा अपडेट्स",

        // Auth & Accounts
        "auth_welcome_back" to "वापसी पर स्वागत है",
        "auth_login_subtitle" to "अपनी परीक्षा तैयारी जारी रखने के लिए साइन इन करें",
        "auth_email_label" to "ईमेल पता",
        "auth_email_hint" to "student@example.com",
        "auth_password_label" to "पासवर्ड",
        "auth_password_hint" to "अपना पासवर्ड दर्ज करें",
        "auth_login_btn" to "साइन इन करें",
        "auth_signup_btn" to "नया खाता बनाएं",
        "auth_dont_have_account" to "खाता नहीं है?",
        "auth_already_have_account" to "पहले से खाता है?",
        "auth_forgot_password" to "पासवर्ड भूल गए?",
        "auth_sign_in_google" to "गूगल के साथ जारी रखें",
        "auth_continue_guest" to "अतिथि के रूप में देखें",
        "auth_create_account_title" to "निःशुल्क खाता बनाएं",
        "auth_name_label" to "पूरा नाम",
        "auth_name_hint" to "आपका नाम",
        "auth_confirm_password" to "पासवर्ड की पुष्टि करें",
        "auth_otp_title" to "सुरक्षा कोड सत्यापित करें",
        "auth_otp_subtitle" to "आपके ईमेल पर भेजा गया 6-अंकीय सत्यापन कोड दर्ज करें",
        "auth_verify_btn" to "सत्यापित करें और आगे बढ़ें",
        "auth_resend_otp" to "कोड पुनः भेजें",
        "auth_sign_out" to "साइन आउट",
        "auth_delete_account" to "खाता हटाएं",

        // Top App Bar & Universal Actions
        "action_back" to "वापस",
        "action_save" to "सहेजें",
        "action_saved" to "सहेजा गया",
        "action_share" to "साझा करें",
        "action_download" to "डाउनलोड",
        "action_search" to "खोजें",
        "action_filter" to "फ़िल्टर",
        "action_sort" to "क्रमबद्ध करें",
        "action_clear" to "साफ़ करें",
        "action_clear_all" to "सभी साफ़ करें",
        "action_apply" to "लागू करें",
        "action_cancel" to "रद्द करें",
        "action_confirm" to "पुष्टि करें",
        "action_done" to "संपन्न",
        "action_close" to "बंद करें",
        "action_refresh" to "ताज़ा करें",
        "action_retry" to "पुनः प्रयास करें",
        "action_delete" to "हटाएं",
        "action_edit" to "संपादित करें",
        "action_view_all" to "सभी देखें",
        "action_view_details" to "विवरण देखें",
        "action_start" to "शुरू करें",
        "action_resume" to "जारी रखें",
        "action_pause" to "रोकें",
        "action_stop" to "समाप्त करें",
        "action_submit" to "जमा करें",
        "action_next" to "अगला",
        "action_previous" to "पिछला",
        "action_switch_language" to "भाषा बदलें",
        "language_current" to "हिन्दी",
        "language_en" to "English",
        "language_hi" to "हिन्दी",

        // Home Screen
        "home_greeting" to "स्वागत है, %s 👋",
        "home_exam_countdown" to "परीक्षा में %d दिन शेष",
        "home_target_exam" to "लक्ष्य परीक्षा: %s",
        "home_daily_missions" to "आज के अध्ययन मिशन",
        "home_all_missions_done" to "सभी मिशन पूरे हुए! शानदार प्रदर्शन 🎉",
        "home_quick_actions" to "त्वरित अध्ययन हब",
        "home_action_learn" to "पढ़ाई और पाठ्यक्रम",
        "home_action_practice" to "मॉक टेस्ट",
        "home_action_updates" to "सरकारी नौकरियां और अपडेट्स",
        "home_action_focus" to "फोकस शील्ड",
        "home_action_nova" to "नोवा एआई से पूछें",
        "home_readiness_score" to "परीक्षा तत्परता स्कोर",
        "home_ai_recommendation" to "एआई स्टडी कोच सिफारिश",
        "home_study_now" to "अभी पढ़ने के लिए अनुशंसित",
        "home_live_updates_title" to "लाइव परीक्षा समाचार व सूचनाएं",
        "home_vacancies_title" to "नवीनतम सरकारी रिक्तियां",
        "home_continue_session" to "अधूरा टेस्ट जारी रखें",

        // Learn Hub & Chapters
        "learn_hub_title" to "अध्ययन और शिक्षण हब",
        "learn_hub_subtitle" to "संपूर्ण पाठ्यक्रम, नोट्स, सूत्र और मुख्य अवधारणाएं",
        "learn_tab_all_subjects" to "पाठ्यक्रम वृक्ष",
        "learn_tab_materials" to "अध्ययन सामग्री",
        "learn_tab_notes" to "स्मार्ट नोट्स",
        "learn_tab_formulas" to "सूत्र संग्रह",
        "learn_tab_current_affairs" to "करेंट अफेयर्स",
        "learn_tab_doubts" to "संदेह निवारण",
        "learn_chapters_count" to "%d अध्याय",
        "learn_topics_count" to "%d विषय",
        "learn_mastery_level" to "दक्षता: %d%%",
        "learn_read_aloud" to "बोलकर सुनाएं",
        "learn_key_points" to "मुख्य सारांश बिंदु",
        "learn_practice_this" to "इस विषय के प्रश्न हल करें",
        "learn_ask_doubt" to "इस विषय पर नोवा से पूछें",
        "learn_mark_mastered" to "पूर्ण चिह्नित करें",

        // Smart Vacancies & Updates Hub
        "vacancy_hub_title" to "सरकारी नौकरियां और परीक्षा अपडेट्स",
        "vacancy_hub_subtitle" to "आधिकारिक अधिसूचनाएं, एडमिट कार्ड, उत्तर कुंजी और परिणाम",
        "vacancy_tab_all" to "रिक्तियां (Jobs)",
        "vacancy_tab_admit_card" to "प्रवेश पत्र (Admit Cards)",
        "vacancy_tab_results" to "परीक्षा परिणाम (Results)",
        "vacancy_tab_answer_key" to "उत्तर कुंजी (Answer Keys)",
        "vacancy_tab_admission" to "प्रवेश (Admission)",
        "vacancy_tab_saved" to "सहेजे गए व ट्रैक किए गए",
        "vacancy_tab_alerts" to "सूचना अलर्ट",
        "vacancy_filter_all_states" to "अखिल भारतीय व राज्य",
        "vacancy_filter_category" to "नौकरी श्रेणी",
        "vacancy_search_placeholder" to "रिक्ति, भर्ती बोर्ड, पद, राज्य खोजें...",
        "vacancy_last_date" to "अंतिम तिथि: %s",
        "vacancy_posts_count" to "%s पद",
        "vacancy_eligibility" to "पात्रता और शैक्षणिक योग्यता",
        "vacancy_age_limit" to "आयु सीमा",
        "vacancy_salary" to "वेतनमान / पे स्केल",
        "vacancy_apply_online" to "ऑनलाइन आवेदन करें (आधिकारिक लिंक)",
        "vacancy_download_pdf" to "आधिकारिक अधिसूचना पीडीएफ",
        "vacancy_selection_process" to "चयन प्रक्रिया",
        "vacancy_syllabus" to "परीक्षा पैटर्न और पाठ्यक्रम",
        "vacancy_important_dates" to "महत्वपूर्ण तिथियां",
        "vacancy_fee_details" to "आवेदन शुल्क",
        "vacancy_set_reminder" to "समय-सीमा रिमाइंडर लगाएं",
        "vacancy_track_application" to "आवेदन ट्रैक करें",
        "vacancy_find_jobs_btn" to "मेरी योग्यता अनुसार नौकरियां खोजें",
        "vacancy_saved_empty" to "अभी कोई सहेजी गई रिक्ति नहीं है।",

        // Focus Mode & App Shield
        "focus_title" to "गहन अध्ययन फोकस सत्र",
        "focus_subtitle" to "सक्रिय ऐप ब्लॉकर के साथ ध्यान भटकाव मुक्त पढ़ाई",
        "focus_start_session" to "फोकस टाइमर शुरू करें",
        "focus_pause_session" to "सत्र रोकें",
        "focus_resume_session" to "फोकस जारी रखें",
        "focus_end_session" to "सत्र समाप्त करें",
        "focus_strict_mode" to "सख्त ऐप लॉक",
        "focus_strict_desc" to "सत्र के दौरान सभी ध्यान भटकाने वाले ऐप्स को रोकता है",
        "focus_take_break" to "5 मिनट का ब्रेक लें",
        "focus_break_running" to "ब्रेक समय सक्रिय",
        "focus_streak_banner" to "🔥 %d दिन की अध्ययन स्ट्रीक!",
        "focus_session_completed" to "सत्र पूरा हुआ! शानदार फोकस 🎉",
        "focus_xp_earned" to "+%d स्टडी XP अर्जित किए",

        // Practice & Mock Tests
        "practice_title" to "टेस्ट सीरीज़ और अभ्यास हब",
        "practice_subtitle" to "पिछले वर्षों के प्रश्न, स्पीड टेस्ट, पूर्ण मॉक और गलती विश्लेषण",
        "practice_start_full_mock" to "पूर्ण मॉक टेस्ट शुरू करें",
        "practice_start_speed_test" to "10 मिनट स्पीड ड्रिल",
        "practice_start_topic_quiz" to "विषय-वार अभ्यास",
        "practice_question_palette" to "प्रश्न पैलेट",
        "practice_mark_review" to "समीक्षा के लिए चिह्नित करें",
        "practice_clear_response" to "उत्तर साफ़ करें",
        "practice_save_next" to "सहेजें और अगला",
        "practice_submit_confirm_title" to "क्या टेस्ट जमा करना चाहते हैं?",
        "practice_submit_confirm_desc" to "क्या आप टेस्ट जमा करने के लिए निश्चित हैं? आपने %d उत्तर दिए हैं, %d समीक्षा के लिए छोड़े हैं, और %d अनुत्तरित हैं।",
        "practice_scorecard_title" to "टेस्ट परिणाम और स्कोरकार्ड",
        "practice_score_label" to "अंक: %d / %d",
        "practice_accuracy_label" to "सटीकता: %.1f%%",
        "practice_time_spent" to "व्यतीत समय: %s",
        "practice_review_solutions" to "चरण-दर-चरण समाधान देखें",
        "practice_retry_wrong" to "गलत प्रश्न पुनः हल करें",
        "practice_mistake_book" to "गलती डायरी (Mistake Book)",

        // NOVA AI Tutor
        "nova_title" to "नोवा एआई शैक्षणिक गुरु",
        "nova_subtitle" to "24/7 व्यक्तिगत परीक्षा संशय निवारक और अवधारणा शिक्षक",
        "nova_prompt_hint" to "कोई भी शैक्षणिक संदेह, सूत्र या अवधारणा पूछें...",
        "nova_thinking_mode" to "गहन चिंतन एवं चरणबद्ध व्युत्पत्ति मोड",
        "nova_quick_actions" to "त्वरित एआई क्रियाएं",
        "nova_action_summarize" to "विषय का सारांश",
        "nova_action_derivation" to "चरण-दर-चरण गणित",
        "nova_action_mcq" to "अभ्यास प्रश्न बनाएं",
        "nova_action_flashcards" to "फ्लैशकार्ड बनाएं",

        // Settings & Profile
        "settings_title" to "सेटिंग्स और खाता",
        "settings_language_section" to "भाषा और स्थानीयकरण 🌐",
        "settings_language_desc" to "पूरे ऐप में अंग्रेजी और हिन्दी के बीच भाषा बदलें",
        "settings_theme_section" to "ऐप थीम और प्रकटन 🎨",
        "settings_notifications_section" to "स्मार्ट सूचनाएं 🔔",
        "settings_exam_section" to "परीक्षा और लक्ष्य 🎓",
        "settings_change_exam" to "चुनी हुई परीक्षा बदलें",
        "settings_daily_hours" to "दैनिक अध्ययन लक्ष्य (घंटे)",
        "settings_clear_cache" to "अनुवाद व ऑफलाइन कैश साफ़ करें",
        "settings_sync_data" to "क्लाउड के साथ डेटा सिंक करें",

        // General States & Messages
        "state_loading" to "लोड हो रहा है...",
        "state_no_data" to "कोई डेटा नहीं मिला",
        "state_error" to "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
        "state_offline" to "ऑफलाइन मोड में काम कर रहे हैं",
        "toast_lang_switched" to "भाषा बदलकर %s कर दी गई है",
        "toast_back_exit" to "स्टडीमेट से बाहर निकलने के लिए दोबारा बैक दबाएं"
    )

    fun get(key: String, language: AppLanguage, vararg args: Any): String {
        val map = when (language) {
            AppLanguage.HINDI -> hindiMap
            AppLanguage.ENGLISH -> englishMap
        }
        val template = map[key] ?: englishMap[key] ?: key
        return if (args.isNotEmpty()) {
            try {
                String.format(template, *args)
            } catch (e: Exception) {
                template
            }
        } else {
            template
        }
    }

    /**
     * Translates common terminology words / headers if a string key isn't provided.
     */
    fun translateWordOrPhrase(text: String, language: AppLanguage): String {
        if (language == AppLanguage.ENGLISH || text.isBlank()) return text
        val trimmed = text.trim()

        // Check if there is an exact key match or value match
        for ((k, enVal) in englishMap) {
            if (enVal.equals(trimmed, ignoreCase = true)) {
                return hindiMap[k] ?: text
            }
        }

        // Common dynamic UI terminology replacements
        val terminologyMap = mapOf(
            "Vacancies" to "रिक्तियां",
            "Vacancy" to "रिक्ति",
            "Admit Cards" to "प्रवेश पत्र",
            "Admit Card" to "प्रवेश पत्र",
            "Results" to "परिणाम",
            "Result" to "परिणाम",
            "Answer Keys" to "उत्तर कुंजी",
            "Answer Key" to "उत्तर कुंजी",
            "Admissions" to "प्रवेश",
            "Admission" to "प्रवेश",
            "Notifications" to "सूचनाएं",
            "Notification" to "अधिसूचना",
            "Latest Updates" to "नवीनतम अपडेट्स",
            "Study Hub" to "अध्ययन हब",
            "Focus Mode" to "फोकस मोड",
            "Practice" to "अभ्यास",
            "AI Tutor" to "एआई ट्यूटर",
            "Chapters" to "अध्याय",
            "Topics" to "विषय",
            "Formulas" to "सूत्र",
            "Current Affairs" to "करेंट अफेयर्स",
            "Syllabus" to "पाठ्यक्रम",
            "Eligibility" to "पात्रता",
            "Apply Online" to "ऑनलाइन आवेदन",
            "Official Website" to "आधिकारिक वेबसाइट",
            "Exam Date" to "परीक्षा तिथि",
            "Last Date" to "अंतिम तिथि",
            "Total Posts" to "कुल पद",
            "Salary" to "वेतनमान",
            "Age Limit" to "आयु सीमा",
            "Qualifications" to "योग्यता",
            "All India" to "अखिल भारतीय",
            "State PSC" to "राज्य लोक सेवा आयोग",
            "Central Govt" to "केंद्र सरकार",
            "Defense / Police" to "रक्षा / पुलिस",
            "Banking / Insurance" to "बैंकिंग / बीमा",
            "Teaching" to "शिक्षण",
            "Engineering / Tech" to "इंजीनियरिंग",
            "Medical / Health" to "चिकित्सा",
            "High Priority" to "उच्च प्राथमिकता",
            "Medium Priority" to "मध्यम प्राथमिकता",
            "Low Priority" to "सामान्य प्राथमिकता"
        )

        var result = trimmed
        for ((enTerm, hiTerm) in terminologyMap) {
            if (result.equals(enTerm, ignoreCase = true)) {
                return hiTerm
            }
        }
        return result
    }
}
